spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/login?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 11

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password: acmroot
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  http:
    encoding:
      charset: UTF-8
      enabled: true


  mail:
    username: acmrecentcontents@aliyun.com
    password: TDWMADJAP98
    default-encoding: UTF-8
    host: smtp.aliyun.com
    port: 25
    properties:
      mail:
        debug: true

#  quartz:
#    auto-startup: true
#    job-store-type: jdbc
#    #初始化表
#    jdbc:
#      initialize-schema: never
#    #属性配置
#    properties:
#      org:
#        quartz:
#          scheduler:
#            #调度器实例名称
#            instanceName: QuartzScheduler
#            #调度器实例编号自动生成
#            instanceId: AUTO
#          jobStore:
#            #持久化方式配置
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            #持久化方式配置数据驱动，MySQL数据库
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            #quartz相关数据表前缀名
#            tablePrefix: QRTZ_
#            #数据源 随便取
#            dataSource: mysql
#            #调度实例失效的检查时间间隔
#            clusterCheckinInterval: 10000
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 500KB

server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    # 下面三行nginx转发tomcat配置
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  address: 127.0.0.1

API: /api/v1
#三分钟内可发送邮件次数
TIMES: 10

SEND_MAIL: true

