spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/login?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT
    username: root
    password: 11

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password: acmroot
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  http:
    converters:
      preferred-json-mapper: gson
    encoding:
      charset: UTF-8
      enabled: true

  mail:
    username: acmrecentcontents@aliyun.com
    password: TDWMADJAP98
    default-encoding: UTF-8
    host: smtp.aliyun.com
    port: 25
    properties:
      mail:
        debug: true

  servlet:
    multipart:
      enabled: true
      location: src/main/resources/img/
      file-size-threshold: 1MB
      max-file-size: 2MB

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

shiro:
  enabled: true
  web:
    enabled: true
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /login
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true

qiniu:
  accessKey: ANJS5owl4TouX7YMZqUwKKKMDWuWJy_PDAIujGVc
  secretKey: GJXLYDM0hXGKAeqXtEbFtnTBIUyviMxkTPGlZ3HZ
  bucket: acmrecentcontents-code
